INSERT into Transaction (id,change_value,user_id) values(1  ,-1.00,2);
INSERT into Transaction (id,change_value,user_id) values(2  ,-0.90,2);
INSERT into Transaction (id,change_value,user_id) values(3  ,-0.80,2);
INSERT into Transaction (id,change_value,user_id) values(4  ,-1.00,2);
INSERT into Transaction (id,change_value,user_id) values(5  ,-0.90,2);
INSERT into Transaction (id,change_value,user_id) values(6  ,-0.80,2);
INSERT into Transaction (id,change_value,user_id) values(7  ,-1.00,2);
INSERT into Transaction (id,change_value,user_id) values(8  ,-0.90,2);
INSERT into Transaction (id,change_value,user_id) values(9  ,-0.80,2);
INSERT into Transaction (id,change_value,user_id) values(10 ,+1.00,2);
INSERT into Transaction (id,change_value,user_id) values(11 ,+0.90,2);
INSERT into Transaction (id,change_value,user_id) values(12 ,+0.80,2);
INSERT into Transaction (id,change_value,user_id) values(13 ,-1.00,2);
INSERT into Transaction (id,change_value,user_id) values(14 ,-0.90,2);
INSERT into Transaction (id,change_value,user_id) values(15 ,-0.80,2);
INSERT into Transaction (id,change_value,user_id) values(16 ,-1.00,2);
INSERT into Transaction (id,change_value,user_id) values(17 ,-0.90,2);
INSERT into Transaction (id,change_value,user_id) values(18 ,-0.80,2);
INSERT into Transaction (id,change_value,user_id) values(19 ,-1.00,3);
INSERT into Transaction (id,change_value,user_id) values(20 ,-0.90,3);
INSERT into Transaction (id,change_value,user_id) values(21 ,-0.80,3);
INSERT into Transaction (id,change_value,user_id) values(22 ,-1.00,3);
INSERT into Transaction (id,change_value,user_id) values(23 ,-0.90,3);
INSERT into Transaction (id,change_value,user_id) values(24 ,-0.80,3);
INSERT into Transaction (id,change_value,user_id) values(25 ,-1.00,3);
INSERT into Transaction (id,change_value,user_id) values(26 ,-0.90,3);
INSERT into Transaction (id,change_value,user_id) values(27 ,-0.80,3);
INSERT into Transaction (id,change_value,user_id) values(28 ,+1.00,3);
INSERT into Transaction (id,change_value,user_id) values(29 ,+0.90,3);
INSERT into Transaction (id,change_value,user_id) values(30 ,+0.80,3);
INSERT into Transaction (id,change_value,user_id) values(31 ,-1.00,3);
INSERT into Transaction (id,change_value,user_id) values(32 ,-0.90,3);
INSERT into Transaction (id,change_value,user_id) values(33 ,-0.80,3);
INSERT into Transaction (id,change_value,user_id) values(34 ,-1.00,3);
INSERT into Transaction (id,change_value,user_id) values(35 ,-0.90,3);
INSERT into Transaction (id,change_value,user_id) values(36 ,-0.80,3);
INSERT into Transaction (id,change_value,user_id) values(37 ,-1.00,4);
INSERT into Transaction (id,change_value,user_id) values(38 ,-0.90,4);
INSERT into Transaction (id,change_value,user_id) values(39 ,-0.80,4);
INSERT into Transaction (id,change_value,user_id) values(40 ,-1.00,4);
INSERT into Transaction (id,change_value,user_id) values(41 ,-0.90,4);
INSERT into Transaction (id,change_value,user_id) values(42 ,-0.80,4);
INSERT into Transaction (id,change_value,user_id) values(43 ,-1.00,4);
INSERT into Transaction (id,change_value,user_id) values(44 ,-0.90,4);
INSERT into Transaction (id,change_value,user_id) values(45 ,-0.80,4);
INSERT into Transaction (id,change_value,user_id) values(46 ,+1.00,4);
INSERT into Transaction (id,change_value,user_id) values(47 ,+0.90,4);
INSERT into Transaction (id,change_value,user_id) values(48 ,+0.80,4);
INSERT into Transaction (id,change_value,user_id) values(49 ,-1.00,4);
INSERT into Transaction (id,change_value,user_id) values(50 ,-0.90,4);
INSERT into Transaction (id,change_value,user_id) values(51 ,-0.80,4);
INSERT into Transaction (id,change_value,user_id) values(52 ,-1.00,4);
INSERT into Transaction (id,change_value,user_id) values(53 ,-0.90,4);
INSERT into Transaction (id,change_value,user_id) values(54 ,-0.80,4);
INSERT into Transaction (id,change_value,user_id) values(55 ,-1.00,5);
INSERT into Transaction (id,change_value,user_id) values(56 ,-0.90,5);
INSERT into Transaction (id,change_value,user_id) values(57 ,-0.80,5);
INSERT into Transaction (id,change_value,user_id) values(58 ,-1.00,5);
INSERT into Transaction (id,change_value,user_id) values(59 ,-0.90,5);
INSERT into Transaction (id,change_value,user_id) values(60 ,-0.80,5);
INSERT into Transaction (id,change_value,user_id) values(61 ,-1.00,5);
INSERT into Transaction (id,change_value,user_id) values(62 ,-0.90,5);
INSERT into Transaction (id,change_value,user_id) values(63 ,-0.80,5);
INSERT into Transaction (id,change_value,user_id) values(64 ,+1.00,5);
INSERT into Transaction (id,change_value,user_id) values(65 ,+0.90,5);
INSERT into Transaction (id,change_value,user_id) values(66 ,+0.80,5);
INSERT into Transaction (id,change_value,user_id) values(67 ,-1.00,5);
INSERT into Transaction (id,change_value,user_id) values(68 ,-0.90,5);
INSERT into Transaction (id,change_value,user_id) values(69 ,-0.80,5);
INSERT into Transaction (id,change_value,user_id) values(70 ,-1.00,5);
INSERT into Transaction (id,change_value,user_id) values(71 ,-0.90,5);
INSERT into Transaction (id,change_value,user_id) values(72 ,-0.80,5);
INSERT into Transaction (id,change_value,user_id) values(73 ,-1.00,6);
INSERT into Transaction (id,change_value,user_id) values(74 ,-0.90,6);
INSERT into Transaction (id,change_value,user_id) values(75 ,-0.80,6);
INSERT into Transaction (id,change_value,user_id) values(76 ,-1.00,6);
INSERT into Transaction (id,change_value,user_id) values(77 ,-0.90,6);
INSERT into Transaction (id,change_value,user_id) values(78 ,-0.80,6);
INSERT into Transaction (id,change_value,user_id) values(79 ,-1.00,6);
INSERT into Transaction (id,change_value,user_id) values(80 ,-0.90,6);
INSERT into Transaction (id,change_value,user_id) values(81 ,-0.80,6);
INSERT into Transaction (id,change_value,user_id) values(82 ,+1.00,6);
INSERT into Transaction (id,change_value,user_id) values(83 ,+0.90,6);
INSERT into Transaction (id,change_value,user_id) values(84 ,+0.80,6);
INSERT into Transaction (id,change_value,user_id) values(85 ,-1.00,6);
INSERT into Transaction (id,change_value,user_id) values(86 ,-0.90,6);
INSERT into Transaction (id,change_value,user_id) values(87 ,-0.80,6);
INSERT into Transaction (id,change_value,user_id) values(88 ,-1.00,6);
INSERT into Transaction (id,change_value,user_id) values(89 ,-0.90,6);
INSERT into Transaction (id,change_value,user_id) values(90 ,-0.80,6);
INSERT into Transaction (id,change_value,user_id) values(91 ,-1.00,7);
INSERT into Transaction (id,change_value,user_id) values(92 ,-0.90,7);
INSERT into Transaction (id,change_value,user_id) values(93 ,-0.80,7);
INSERT into Transaction (id,change_value,user_id) values(94 ,-1.00,7);
INSERT into Transaction (id,change_value,user_id) values(95 ,-0.90,7);
INSERT into Transaction (id,change_value,user_id) values(96 ,-0.80,7);
INSERT into Transaction (id,change_value,user_id) values(97 ,-1.00,7);
INSERT into Transaction (id,change_value,user_id) values(98 ,-0.90,7);
INSERT into Transaction (id,change_value,user_id) values(99 ,-0.80,7);
INSERT into Transaction (id,change_value,user_id) values(100,+1.00,7);
INSERT into Transaction (id,change_value,user_id) values(101,+0.90,7);
INSERT into Transaction (id,change_value,user_id) values(102,+0.80,7);
INSERT into Transaction (id,change_value,user_id) values(103,-1.00,7);
INSERT into Transaction (id,change_value,user_id) values(104,-0.90,7);
INSERT into Transaction (id,change_value,user_id) values(105,-0.80,7);
INSERT into Transaction (id,change_value,user_id) values(106,-1.00,7);
INSERT into Transaction (id,change_value,user_id) values(107,-0.90,7);
INSERT into Transaction (id,change_value,user_id) values(108,-0.80,7);
INSERT into Transaction (id,change_value,user_id) values(109,-1.00,8);
INSERT into Transaction (id,change_value,user_id) values(110,-0.90,8);
INSERT into Transaction (id,change_value,user_id) values(111,-0.80,8);
INSERT into Transaction (id,change_value,user_id) values(112,-1.00,8);
INSERT into Transaction (id,change_value,user_id) values(113,-0.90,8);
INSERT into Transaction (id,change_value,user_id) values(114,-0.80,8);
INSERT into Transaction (id,change_value,user_id) values(115,-1.00,8);
INSERT into Transaction (id,change_value,user_id) values(116,-0.90,8);
INSERT into Transaction (id,change_value,user_id) values(117,-0.80,8);
INSERT into Transaction (id,change_value,user_id) values(118,+1.00,8);
INSERT into Transaction (id,change_value,user_id) values(119,+0.90,8);
INSERT into Transaction (id,change_value,user_id) values(120,+0.80,8);
INSERT into Transaction (id,change_value,user_id) values(121,-1.00,8);
INSERT into Transaction (id,change_value,user_id) values(122,-0.90,8);
INSERT into Transaction (id,change_value,user_id) values(123,-0.80,8);
INSERT into Transaction (id,change_value,user_id) values(124,-1.00,8);
INSERT into Transaction (id,change_value,user_id) values(125,-0.90,8);
INSERT into Transaction (id,change_value,user_id) values(126,-0.80,8);
INSERT into Transaction (id,change_value,user_id) values(127,-1.00,9);
INSERT into Transaction (id,change_value,user_id) values(128,-0.90,9);
INSERT into Transaction (id,change_value,user_id) values(129,-0.80,9);
INSERT into Transaction (id,change_value,user_id) values(130,-1.00,9);
INSERT into Transaction (id,change_value,user_id) values(131,-0.90,9);
INSERT into Transaction (id,change_value,user_id) values(132,-0.80,9);
INSERT into Transaction (id,change_value,user_id) values(133,-1.00,9);
INSERT into Transaction (id,change_value,user_id) values(134,-0.90,9);
INSERT into Transaction (id,change_value,user_id) values(135,-0.80,9);
INSERT into Transaction (id,change_value,user_id) values(136,+1.00,9);
INSERT into Transaction (id,change_value,user_id) values(137,+0.90,9);
INSERT into Transaction (id,change_value,user_id) values(138,+0.80,9);
INSERT into Transaction (id,change_value,user_id) values(139,-1.00,9);
INSERT into Transaction (id,change_value,user_id) values(140,-0.90,9);
INSERT into Transaction (id,change_value,user_id) values(141,-0.80,9);
INSERT into Transaction (id,change_value,user_id) values(142,-1.00,9);
INSERT into Transaction (id,change_value,user_id) values(143,-0.90,9);
INSERT into Transaction (id,change_value,user_id) values(144,-0.80,9);
INSERT into Transaction (id,change_value,user_id) values(145,-1.00,10);
INSERT into Transaction (id,change_value,user_id) values(146,-0.90,10);
INSERT into Transaction (id,change_value,user_id) values(147,-0.80,10);
INSERT into Transaction (id,change_value,user_id) values(148,-1.00,10);
INSERT into Transaction (id,change_value,user_id) values(149,-0.90,10);
INSERT into Transaction (id,change_value,user_id) values(150,-0.80,10);
INSERT into Transaction (id,change_value,user_id) values(151,-1.00,10);
INSERT into Transaction (id,change_value,user_id) values(152,-0.90,10);
INSERT into Transaction (id,change_value,user_id) values(153,-0.80,10);
INSERT into Transaction (id,change_value,user_id) values(154,+1.00,10);
INSERT into Transaction (id,change_value,user_id) values(155,+0.90,10);
INSERT into Transaction (id,change_value,user_id) values(156,+0.80,10);
INSERT into Transaction (id,change_value,user_id) values(157,-1.00,10);
INSERT into Transaction (id,change_value,user_id) values(158,-0.90,10);
INSERT into Transaction (id,change_value,user_id) values(159,-0.80,10);
INSERT into Transaction (id,change_value,user_id) values(160,-1.00,10);
INSERT into Transaction (id,change_value,user_id) values(161,-0.90,10);
INSERT into Transaction (id,change_value,user_id) values(162,-0.80,10);